## Configuration for the kallisto_10x Snakemake workflow.
## Written by David McKellar
## Last edited:

########################################################################################################
# Run settings
########################################################################################################

# sample name, pointing to cellranger count output directory (same as the ""--id" input for cellranger count)
SAMPLE_SHEET: ./sample_sheet.csv #TODO

# fastq files should be named like this: sampleID + FQ_EXTENSION1 + 'R1' + FQ_EXTENSION2
FQ_EXTENSION1: ''
FQ_EXTENSION1: '.fastq.gz'

# kallisto parameters
#TODO
CORES: 10 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")
UMIlen: 12 #v2=__, v3=12

########################################################################################################
# Important directory file paths
########################################################################################################
DATADIR: /workdir/dwm269/totalRNA/data/cr_count/mm39 # directory where cellranger_count outputs are stored - be sure to use an absolute path (starting with root)
TMPDIR: ./tmp # directory for temporary files
OUTDIR: /workdir/dwm269/totalRNA/data/kallisto/mm39/

########################################################################################################
# Executables - file paths
########################################################################################################
KAL_EXEC: kallisto #TODO
BUS_EXEC: bustools #TODO
########################################################################################################
# Resources - file paths
########################################################################################################
KAL_REF: /workdir/dwm269/genomes/mm39_kallisto #TODO
KAL_GENES: #TODO

CB_WHITELIST: ./resources/barcodes_10x/3M-february-2018.txt # path to cell barcodes (CB) whitelist, gunzipped (without the .gz extension) - https://kb.10xgenomics.com/hc/en-us/articles/115004506263-What-is-a-barcode-whitelist-
