########################################################################################################
# kallisto_10x
#   Snakemake workflow to use kallisto to align and quantify 10x Chromium datasets
#   v1.0
#   Written by David McKellar
#   Last edited: 5/10/21, DWM
########################################################################################################

import pdb
import pandas as pd
########################################################################################################
# Config file
########################################################################################################
configfile:'config.yaml'
########################################################################################################
# Directories and locations
########################################################################################################
DATADIR = config['DATADIR']
TMPDIR = config['TMPDIR']
OUTDIR = config['OUTDIR']

########################################################################################################
# Variables and references
########################################################################################################
SAMPLE = list(pd.read_table(config['SAMPLE_SHEET'], names=['sample', 'fq_dir'])['sample'])
DATADIR = list(pd.read_table(config['SAMPLE_SHEET'], names=['sample', 'fq_dir'])['fq_dir'])

KAL_REF = config['KAL_REF']
FQ_EXTENSION = config['FQ_EXTENSION']

########################################################################################################
# Executables
########################################################################################################
KALEXEC = config['KALEXEC']

########################################################################################################
rule all:
    input:
        expand(INSERT_OUTPUT_HERE ,DATADIR=config['DATADIR'], sample=config['Samples'])

#############################################
## Pre-alignment set up
#############################################
# Unzip the whitelist file if it hasn't been done yet
rule gunzipWhitelist:
    input:
        config['CB_WHITELIST']+'.gz'
    output:
        config['CB_WHITELIST']
    shell:
    """
        gunzip {input}
    """

#############################################
## Alignment
#############################################
# Make output directory, align fastqs, and generate first-pas raw/filtered feature/cell-barcode matrices
#   Info for kallisto command line paramaters: https://pachterlab.github.io/kallisto/manual
rule: kallisto_align:
    input:#TODO
        R1_FQ = {DATADIR}/{sample} + FQ_EXTENSION1 + 'R1' + FQ_EXTENSION2,
        R2_FQ = {DATADIR}/{sample} + FQ_EXTENSION1 + 'R2' + FQ_EXTENSION2,
        CB_WHITELIST = config['CB_WHITELIST']
    output:#TODO
        SORTEDBAM = {OUTDIR}/{sample}_kallisto/Aligned.sortedByCoord.out.bam, #TODO
        RAWMAT = {OUTDIR}/{sample}_kallisto/Gene/raw/matrix.mtx, #TODO
        FILTEREDMAT = {OUTDIR}/{sample}_kallisto/Gene/filtered/matrix.mtx #TODO
    params:#TODO
        OUTDIR = config['OUTDIR'],
        KAL_EXEC = config['KAL_EXEC'],
        KAL_REF = config['KAL_REF'],
        UMIlen = config['UMIlen']
    threads:
        config['CORES']
    shell: #TODO
        """
        mkdir -p {params.OUTDIR}/{sample}/

        {params.KALEXEC} \
        --runThreadN {threads} \
        --outFileNamePrefix {params.OUTDIR}/{sample}_kallisto/ \
        --outSAMtype BAM SortedByCoordinate \
        --readFilesCommand zcat \
        --soloUMIlen {params.UMIlen} \
        --genomeDir {params.KAL_REF} \
        --genomeLoad LoadAndKeep \
        --readFilesIn {input.R2_FQ} {input.R1_FQ} \
        --soloType CB_UMI_Simple \
        --soloCBwhitelist {input.CB_WHTELIST} \
        --soloCellFilter EmptyDrops_CR
        """

# KAL \
# --runThreadN 24 \
# --outFileNamePrefix ./test/kallisto_ \
# --outSAMtype BAM SortedByCoordinate \
# --readFilesCommand zcat \
# --soloUMIlen 12 \
# --genomeDir /workdir/dwm269/genomes/mm39_STAR \
# --readFilesIn /workdir/dwm269/totalRNA/data/fastq/cr_mkfastq-MiniSeq-C2Cnuc_yPAP1-C2Cnuc_ctrl1/outs/fastq_path/yPAP/C2Cnuc_yPAP1/C2Cnuc_yPAP1_S1_L001_R2_001.fastq.gz /workdir/dwm269/totalRNA/data/fastq/cr_mkfastq-MiniSeq-C2Cnuc_yPAP1-C2Cnuc_ctrl1/outs/fastq_path/yPAP/C2Cnuc_yPAP1/C2Cnuc_yPAP1_S1_L001_R1_001.fastq.gz \
# --soloType CB_UMI_Simple \
# --soloCBwhitelist /home/dwm269/DWM_utils/sc_utils/kallisto_10x_snakemake/resources/barcodes_10x/3M-february-2018.txt \
# --soloCellFilter EmptyDrops_CR

#############################################
## Counting transcripts
#############################################

#TODO

# Re-count multi transcripts, but account for multi-mapping reads. Uses EM to distribute reads across loci
#   requires KAL version >= 2.9
# rule kallisto_multiMap_EM:
#     input:
#         RAWMATDIR = {OUTDIR}/{sample}_kallisto/Gene/raw
#     output:
#
#     params:
#
#     shell:
#     """
#     $STAR_EXEC \
#     --runMode soloCellFiltering \
#     {input.RAWMATDIR} \
#     /path/to/output/prefix   \
#     --soloCellFilter EmptyDrops_CR \
#     --soloMultiMappers EM
#     """

#TODO rule bamToSplitBigWig
