## Configuration for the STARsolo_10x Snakemake workflow.

########################################################################################################
# Run settings
########################################################################################################

# Sample sheet requires a sampleID, and locations of fastqs for R1 and R2
#     For multi-lane inputs, use the following format (from STARsolo github page):
#       --readFilesIn Read2_Lane1.fastq.gz,Read2_Lane2.fastq.gz,Read2_Lane3.fastq.gz  Read1_Lane1.fastq.gz,Read1_Lane2.fastq.gz,Read1_Lane3.fastq.gz

# SAMPLE_SHEET: sample_sheets/Vis_yPAP1-sample_sheet.csv
# SAMPLE_SHEET: sample_sheets/C2Cnuc_yPAP-sample_sheet.csv
SAMPLE_SHEET: sample_sheets/All_yPAP_chromium-sample_sheet.csv
# SAMPLE_SHEET: sample_sheet.csv

# STARsolo parameters
CORES: 12 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")
MEMLIMIT: 50000000000 # limit in bytes
UMIlen: 12 #v2=__, v3=12

########################################################################################################
# Important directory file paths
########################################################################################################
TMPDIR: tmp # directory for temporary files
OUTDIR: /workdir/dwm269/totalRNA/data/STARsolo/GRCm39_GENCODEM27

########################################################################################################
# Executables - file paths
########################################################################################################
STAR_EXEC: /programs/STAR/STAR #biohpc current version of STAR
FASTQC_EXEC: fastqc
BAM2SPLITBW: /home/dwm269/DWM_utils/seq_utils/bam2splitBigWig.sh #Custom function in DWM_utils that splits a bam file by strand and converts it into bigwig format
FASTX_COLLAPSER: fastx_collapser
BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored

########################################################################################################
# Resources - file paths
########################################################################################################
STAR_REF: /workdir/dwm269/genomes/mm39_all/GRCm39_STAR_GENCODE_M27 # path to STAR-formatted reference genome
GENES_GTF: /workdir/dwm269/genomes/mm39_all/GENCODE_M27/gencode.vM27.chr_patch_hapl_scaff.annotation.gtf
CB_WHITELIST: resources/barcodes_10x/3M-february-2018.txt # path to cell barcodes (CB) whitelist, gunzipped (without the .gz extension) - https://kb.10xgenomics.com/hc/en-us/articles/115004506263-What-is-a-barcode-whitelist-
