## Configuration for the STARsolo_10x Snakemake workflow.

########################################################################################################
# Run settings
########################################################################################################

# Sample sheet requires a sampleID, and locations of fastqs for R1 and R2
SAMPLE_SHEET: sample_sheet.csv

# STARsolo parameters
CORES: 25 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")
MEMLIMIT: 50000000000 # limit in bytes
UMIlen: 12 #v2=__, v3=12

########################################################################################################
# Important directory file paths
########################################################################################################
# DATADIR: /workdir/dwm269/totalRNA/data/cr_count/mm10 # directory where cellranger_count outputs are stored - be sure to use an absolute path (starting with root)
TMPDIR: tmp # directory for temporary files
OUTDIR: /workdir/dwm269/totalRNA/data/STARsolo/mm10_SSTsettings

########################################################################################################
# Executables - file paths
########################################################################################################
STAR_EXEC: /programs/STAR/STAR #biohpc current version of STAR
FASTQC_EXEC: fastqc
BAM2SPLITBW: /home/dwm269/DWM_utils/seq_utils/bam2splitBigWig.sh #Custom function in DWM_utils that splits a bam file by strand and converts it into bigwig format
FASTX_COLLAPSER: fastx_collapser
BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored

########################################################################################################
# Resources - file paths
########################################################################################################
STAR_REF: /workdir/dwm269/genomes/mm10_all/mm10_STAR_refGene_transcript # path to STAR-formatted reference genome
CB_WHITELIST: resources/barcodes_10x/3M-february-2018.txt # path to cell barcodes (CB) whitelist, gunzipped (without the .gz extension) - https://kb.10xgenomics.com/hc/en-us/articles/115004506263-What-is-a-barcode-whitelist-
