## Configuration for the kallisto_10x Snakemake workflow.

########################################################################################################
# Run settings
########################################################################################################
#TODO- check
# Sample sheet requires a sampleID, and locations of fastqs for R1 and R2
#     For multi-lane inputs, use the following format (from kallisto github page):
#       --readFilesIn Read2_Lane1.fastq.gz,Read2_Lane2.fastq.gz,Read2_Lane3.fastq.gz  Read1_Lane1.fastq.gz,Read1_Lane2.fastq.gz,Read1_Lane3.fastq.gz

## ~~~~~ Visium sample sheets ~~~~~
# SAMPLE_SHEET: ~/DWM_utils/sample_sheets/All-Vis_HeartREO-sample_sheet.csv
SAMPLE_SHEET: ~/DWM_utils/sample_sheets/All-Vis_yPAP-sample_sheet.csv

## ~~~~~ Chromium sample sheets ~~~~~
# SAMPLE_SHEET: sample_sheets/C2Cnuc_yPAP-sample_sheet.csv
# SAMPLE_SHEET: sample_sheets/All_yPAP_chromium-sample_sheet.csv
# SAMPLE_SHEET: sample_sheets/All_primary_yPAP_chromium-sample_sheet.csv
# SAMPLE_SHEET: sample_sheets/scMuscle2-sample_sheet.csv
# SAMPLE_SHEET: sample_sheets/Ma_iPSC-sample_sheet.csv

# SAMPLE_SHEET: sample_sheet.csv

# kallisto parameters
CORES: 8 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")
MEMLIMIT: 32G # limit in bytes
UMIlen: 12 #v2=__, v3=12, visium=12

## Cell Barcode white lists
# CB_WHITELIST: resources/barcodes_10x/3M-february-2018.txt # path to cell barcodes (CB) whitelist, gunzipped (without the .gz extension) - https://kb.10xgenomics.com/hc/en-us/articles/115004506263-What-is-a-barcode-whitelist-
CB_WHITELIST: resources/barcodes_10x/visium-v1.txt # whitelist for Visium

########################################################################################################
# Important directory file paths
########################################################################################################
TMPDIR: /workdir/dwm269/totalRNA/tmp # directory for temporary files
OUTDIR: /workdir/dwm269/totalRNA/data/kallisto/GRCm39_GENCODEM27
# OUTDIR: /workdir/dwm269/totalRNA/data/kallisto/GRCm39_GENCODEM27_Visium/REO
DATADIR: /workdir/dwm269/scMuscle2/data/fastqs

# TMPDIR: /workdir/dwm269/ma_ipsc/tmp
# OUTDIR: /workdir/dwm269/ma_ipsc/data/kallisto/GRCh38p13
# DATADIR: /workdir/dwm269/ma_ipsc/fastqs

########################################################################################################
# Executables - file paths
########################################################################################################
KB_EXEC: kb
FASTQC_EXEC: fastqc
BAM2SPLITBW: /home/dwm269/DWM_utils/seq_utils/bam2splitBigWig.sh #Custom function in DWM_utils that splits a bam file by strand and converts it into bigwig format
FASTX_COLLAPSER: fastx_collapser
BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored

########################################################################################################
# Resources - file paths
########################################################################################################
### Mouse ###
KB_IDX: /workdir/dwm269/genomes/mm39_all/GRCm39_kallisto_GENCODE_M27/transcriptome.idx # path to kallisto index file
KB_T2G: /workdir/dwm269/genomes/mm39_all/GRCm39_kallisto_GENCODE_M27/transcripts_to_genes.txt # path to transcripts_to_genes.txt
FASTA: /workdir/dwm269/genomes/mm39_all/GENCODE_M27/GRCm39.genome.fa # primary assembly
GENES_GTF: /workdir/dwm269/genomes/mm39_all/GENCODE_M27/gencode.vM27.chr_patch_hapl_scaff.annotation.gtf # annotations used to generate .idx & T2G

### Mouse + Reovirus-T1L###
#TODO

### Human ###
#TODO
