## Configuration for the STARsolo_10x Snakemake workflow.

########################################################################################################
# Run settings
########################################################################################################

# Sample sheet requires a sampleID, and locations of fastqs for R1 and R2
#     For multi-lane inputs, use the following format (from STARsolo github page):
#       --readFilesIn Read2_Lane1.fastq.gz,Read2_Lane2.fastq.gz,Read2_Lane3.fastq.gz  Read1_Lane1.fastq.gz,Read1_Lane2.fastq.gz,Read1_Lane3.fastq.gz

## ~~~~~ Visium sample sheets ~~~~~
# SAMPLE_SHEET_PATH: /home/dwm269/DWM_utils/sample_sheets/All-Vis_HeartREO-sample_sheet.csv
# SAMPLE_SHEET_PATH: /home/dwm269/DWM_utils/sample_sheets/AllClean-Vis_yPAP-sample_sheet.csv
# SAMPLE_SHEET_PATH: ~/DWM_utils/sample_sheets/All-Vis_SkM-sample_sheet.csv
# SAMPLE_SHEET_PATH: /home/dwm269/DWM_utils/sample_sheets/test-sample_sheet.csv
# SAMPLE_SHEET_PATH: ~/DWM_utils/sample_sheets/vy5-sample_sheet.csv

## ~~~~~ Chromium sample sheets ~~~~~
# SAMPLE_SHEET_PATH: /home/dwm269/DWM_utils/sample_sheets/C2Cnuc_yPAP-sample_sheet.csv
# SAMPLE_SHEET_PATH: /home/dwm269/DWM_utils/sample_sheets/All_yPAP_chromium-sample_sheet.csv
# SAMPLE_SHEET_PATH: /home/dwm269/DWM_utils/sample_sheets/All_primary_yPAP_chromium-sample_sheet.csv
# SAMPLE_SHEET_PATH: /home/dwm269/DWM_utils/sample_sheets/scMuscle2-sample_sheet.csv
# SAMPLE_SHEET_PATH: /home/dwm269/DWM_utils/sample_sheets/Ma_iPSC-sample_sheet_v2.csv
SAMPLE_SHEET_PATH: /home/dwm269/DWM_utils/sample_sheets/Butcher_KD-sample_sheet.csv


# STARsolo parameters
CORES: 8 # how many cores to give for each process (snakemake automatically parallelizes process using "snakemake -j {numTotalCores}")
MEMLIMIT: 50000000000 # limit in bytes
UMIlen: 12 #v2=10, v3=12, visium=12

## Chemistry details (whitelists, barcode/UMI design, etc.)
CHEMISTRY_SHEET: resources/chemistry_sheet.csv

## Cell Barcode white lists - https://kb.10xgenomics.com/hc/en-us/articles/115004506263-What-is-a-barcode-whitelist-
CB_WHITELIST: resources/barcodes_10x/3M-february-2018.txt # path to cell barcodes (CB) whitelist for v3/3.1 chromium chemistries, gunzipped (without the .gz extension) -
# CB_WHITELIST: resources/barcodes_10x/visium-v1.txt # whitelist for Visium

########################################################################################################
# Important directory file paths
########################################################################################################
# TMPDIR: /workdir/dwm269/totalRNA/tmp # directory for temporary files
# OUTDIR: /workdir/dwm269/totalRNA/data/STARsolo/GRCm39_GENCODEM28_Chromium
# OUTDIR: /workdir/dwm269/totalRNA/data/STARsolo/GRCm39_GENCODEM27_Visium
# OUTDIR: /workdir/dwm269/totalRNA/data/STARsolo/GRCm39_GENCODEM28_Visium/FLExDUX4

# TMPDIR: /workdir/dwm269/scCardiacOrganoid/tmp
# OUTDIR: /workdir/dwm269/scCardiacOrganoid/data/STARsolo/GRCh38p13

TMPDIR: /workdir/dwm269/butcher_kd/tmp
OUTDIR: /workdir/dwm269/butcher_kd/data/STARsolo/Sus_scrofa_EGFP


########################################################################################################
# Executables - file paths
########################################################################################################
#TODO - add umi_tools, etc
STAR_EXEC: /programs/STAR/STAR # 2.7.9a - *Note, had seg fault issues w/ conda version 2.7.10a
CUTADAPT_EXEC: cutadapt
FASTQC_EXEC: fastqc
SAMTOOLS_EXEC: samtools
UMITOOLS_EXEC: umi_tools
QUALIMAP_EXEC: qualimap
BAM2SPLITBW: /home/dwm269/DWM_utils/seq_utils/bam2splitBigWig.sh #Custom function in DWM_utils that splits a bam file by strand and converts it into bigwig format
FASTX_COLLAPSER: fastx_collapser
BLASTDB: /shared_data/genome_db/BLAST_NCBI # path to where the nt BLAST database is stored
PICARD_EXEC: /home/dwm269/miniconda3/envs/STARsolo/share/picard-2.26.10-0/picard.jar

########################################################################################################
# Resources - file paths
########################################################################################################
### Mouse ###
# STAR_REF: /workdir/dwm269/genomes/mm39_all/STAR_GRCm39_GENCODEM28 # path to STAR-formatted reference genome
# GENES_GTF: /workdir/dwm269/genomes/mm39_all/GENCODE_M28/gencode.vM28.chr_patch_hapl_scaff.annotation.gtf
# STAR_MIRBASE_REF: /workdir/dwm269/genomes/mm39_all/STAR_mirbase_mirge
# SPECIES: mouse # species passed to mirge3.0
# MIRGE_LIB: /home/dwm269/usr/bin/miRge3_Lib

### Mouse + Reovirus-T1L###
# STAR_REF: /workdir/dwm269/genomes/mm39_all/STAR_GRCm39_GENCODEM28_REOT1L-as # path to STAR-formatted reference genome
# GENES_GTF: /workdir/dwm269/genomes/mm39_all/STAR_GRCm39_GENCODEM28_REOT1L-as/GRCm39_ReoT1L_merged_genes.gtf


### Mouse + FLExDUX4 ###
# STAR_REF: /workdir/dwm269/genomes/mm39_all/STAR_GRCm39_GENCODEM28_FLExDUX4 # path to STAR-formatted reference genome
# GENES_GTF: /workdir/dwm269/genomes/mm39_all/STAR_GRCm39_GENCODEM28_FLExDUX4/GRCm39_FLExDUX4.gtf

### Human (Homo sapiens)###
# STAR_REF: /workdir/dwm269/genomes/GRCh38_all/GRCh38p13_STAR # path to STAR-formatted reference genome
# GENES_GTF: /workdir/dwm269/genomes/GRCh38_all/GENCODE_GRCh38p13/gencode.v38.chr_patch_hapl_scaff.annotation.gtf
# SPECIES: human # species passed to mirge3.0
# MIRGE_LIB: /home/dwm269/usr/bin/miRge3_Lib

### Pig (Sus scrofa)###
STAR_REF: /workdir/dwm269/genomes/sus_scrofa/sus_scrofa_EGFP_STAR
GENES_GTF: /workdir/dwm269/genomes/sus_scrofa/sus_scrofa_EGFP_STAR/Sus_scrofa_EGFP.gtf
SPECIES: pig # species passed to mirge3.0
MIRGE_LIB: /home/dwm269/usr/bin/miRge3_Lib
